import { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Sidebar } from "@/components/sidebar/collapsible";
import { SidebarProvider } from "@/components/sidebar/provider";
import { ThemeProvider } from "@/components/theme/provider";
import { ToastProvider } from "@/components/ui/toast";
import Header from "@/components/layout/header";
import { Footer } from "@/components/layout/footer";
import Script from "next/script";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en" suppressHydrationWarning>
            <Script src="https://kit.fontawesome.com/40c3b5129c.js" crossOrigin="anonymous" />
            <body className={`${geistSans.variable} ${geistMono.variable} antialiased flex h-screen`} >
                <ThemeProvider>
                    <SidebarProvider>
                        <ToastProvider>
                            <Sidebar />
                            <div className="flex-1 flex flex-col bg-base-100 min-h-screen pb-auto">
                                <Header />
                                {children}
                                <Footer />
                            </div>
                        </ToastProvider>
                    </SidebarProvider>
                </ThemeProvider>
            </body>
        </html >
    );
}
